@startuml

package "Kotlin Client" {
    [Ui] as Ui
    [Client] as Client

    Client -[hidden]- Ui
}

package "RPI Server" {
    [Server] as Server
    [Session] as Session
    [Application] as Application
    [CO2Sensor] as CO2Sensor
    [SQLiteDatabase] as SQLiteDatabase

    Server --> Session : creates sessions
    Session -> Application : DoTaskCallback
    Session <- Application : SendResponseCallback
    Application ..> CO2Sensor : uses
    Application ..> SQLiteDatabase : uses 
}

Client -> Server : http://localhost:8001

@enduml
